# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://luisferreira97.github.io/nbdev-tutorial/"

git_url = "https://github.com/luisferreira97/nbdev-tutorial/tree/main/"

def custom_doc_links(name): return None
